-- MySQL Script generated by MySQL Workbench
-- Tue May  5 17:33:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `ClientID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NOT NULL,
  `Password` VARCHAR(1024) NOT NULL,
  `Description` VARCHAR(1024) NULL DEFAULT 'Keine Beschreibung vorhanden.',
  `ProfilepictureURL` VARCHAR(128) NULL DEFAULT 'Kein Profilbild vorhanden',
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ClientID`),
  UNIQUE INDEX `ClientID_UNIQUE` (`ClientID` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Assignment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Assignment` (
  `AssignmentID` INT NOT NULL AUTO_INCREMENT,
  `ClientFK` INT NOT NULL,
  `Title` VARCHAR(128) NOT NULL,
  `Description` VARCHAR(1024) NOT NULL,
  `Site` ENUM('OnSite', 'Hybrid', 'Remote') NOT NULL DEFAULT 'OnSite',
  `Site_ZipCode` VARCHAR(5) NULL,
  `Site_Addres` VARCHAR(50) NULL,
  `HourlyRate` DECIMAL(5,2) NOT NULL,
  `TimeRequired` INT NOT NULL,
  `AssistenceSystems` JSON NOT NULL,
  `RequiredNeeds` JSON NOT NULL,
  `State` ENUM('Active', 'Done', 'Pending', 'Canceled') NOT NULL,
  `CreatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EndTime` DATETIME NOT NULL COMMENT 'Zeit bis man sich zur Assignment anmelden kann.',
  `TestStart` DATETIME NOT NULL COMMENT 'TestStart muss nach EndTime sein.',
  `TestEnd` DATETIME NOT NULL,
  `GeoPos` POINT NOT NULL,
  PRIMARY KEY (`AssignmentID`),
  UNIQUE INDEX `AuftragID_UNIQUE` (`AssignmentID` ASC),
  INDEX `ClientFK_idx` (`ClientFK` ASC),
  CONSTRAINT `ClientFK`
    FOREIGN KEY (`ClientFK`)
    REFERENCES `mydb`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tester` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tester` (
  `TesterID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `SurName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(1024) NOT NULL,
  `ZipCode` VARCHAR(5) NOT NULL,
  `Adress` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `ProfilepictureURL` VARCHAR(128) NULL DEFAULT 'Kein Profilbild Vorhanden.',
  `Needs` JSON NOT NULL,
  `AssistenceSystems` JSON NULL,
  `WorkingSite` ENUM('OnSite', 'Hybrid', 'Remote') NOT NULL DEFAULT 'OnSite',
  `GeoPos` POINT NOT NULL,
  PRIMARY KEY (`TesterID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assignment_has_Tester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Assignment_has_Tester` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Assignment_has_Tester` (
  `TesterFK` INT NOT NULL,
  `AssignmentFK` INT NOT NULL,
  PRIMARY KEY (`TesterFK`, `AssignmentFK`),
  UNIQUE INDEX `TesterFK_UNIQUE` (`TesterFK` ASC),
  UNIQUE INDEX `AssignmentFK_UNIQUE` (`AssignmentFK` ASC),
  CONSTRAINT `AssignmentFK`
    FOREIGN KEY (`AssignmentFK`)
    REFERENCES `mydb`.`Assignment` (`AssignmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TesterFK`
    FOREIGN KEY (`TesterFK`)
    REFERENCES `mydb`.`Tester` (`TesterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
